### ISSUE TITLE
Extensibility

### ISSUE THREAD

**Issue by hildjj** [stackevo/spudreq#10]
In https://github.com/stackevo/spudreq/blob/master/draft-trammell-spud-req.md#extensibility, we should mention extensibility in the pdec's and adec's.

**Comment by mirjak** [comment]
Should we add one sentence: SPUD must provide a mechanism to extend the SPUD vocabulary"? Is this sufficient? Or do we need to define vocabulary then?

**Comment by hildjj** [comment]
No need to define the vocabulary here.  We could just change the section to say:

SPUD must enable multiple new transport semantics and application/path declarations without requiring updates to SPUD implementations in middleboxes.
