### ISSUE TITLE
SPUD headers

### ISSUE THREAD

**Issue by ekr** [stackevo/spudreq#4]
The document says:  
   Grouping of Packets: : Transport semantics and many properties of
   communication that endpoints may want to expose to middleboxes are
   bound to flows or groups of flows.  SPUD must therefore provide a
   basic facility for associating packets together (into what we call a
   "tube" for lack of a better term) and associate information to these
   groups of packets.  If SPUD is used, all packets of a 5-tuple flow
   must carry the SPUD header, however, not all packets of the same
   5-tuple need to have the same tube ID but all paket with the same
   tube IP need to belong to the same 5-tuple.

Why need this be the case?  This is going to chew up a lot of bandwidth.
If I ensure that I never create two different tubes with the same 5-tuple
in overlapping time frames, what is the tube-ID doing for us on each
packet?

**Comment by mirjak** [comment]
Right, this was phrased wrongly. It should probably say: "Only packet with the same tube ID and same 5-tuple belong to the same tube." Does this make more sense?

**Comment by ekr** [comment]
Yeah that seems reasonable
